.\" Manpage for kalyba.
.\" Contact sirjosephporterkcb@hotmail.com to correct errors or typos.
.TH man 1 "05 May 2024" "0.1" "kalyba man page"
.SH NAME
kalyba \- A file lauching CLI written in bash
.SH SYNOPSIS
kalyba [-AsFc]  
.SH CONFIG
Append 'fileType command' to config. See README for more info.
.SH OPTIONS

.B -A 
excludes . and .. from selection

.B -s 
excludes files starting with . from selection

.B -F 
includes * for files and / for directories

.B -c
disables clearing the ouput after each file selection

.SH BUGS
Not any known.
.SH AUTHOR
DayOfHeat
.SH COPYRIGHT
BSD 3-Clause License, see LICENSE for more info.
